Add Optional CUP_Variants component
Theseus-Aegis/TheseusServices pull request #143
Opened 2020-10-28 22:58 UTC by TyroneMF

- currently only has a lonesome C130J in Theseus colours.

2020-10-28 23:03 UTC, jonpas requested changes

2020-10-28 23:03 UTC, jonpas commented on optionals/variants_cup/CfgVehicles.hpp
> +        class textureSources {
```suggestion
        class TextureSources {
```

2020-10-28 23:03 UTC, jonpas commented on optionals/variants_cup/CfgVehicles.hpp
> +            class TACS {
```suggestion
            class ADDON {
```

2020-10-28 23:06 UTC, jonpas requested changes

2020-10-28 23:06 UTC, jonpas commented on optionals/variants_cup/CfgVehicles.hpp
> +        hiddenSelections[] = {"camo1","camo2"};
```suggestion
        hiddenSelections[] = {"camo1", "camo2"};
```

2020-11-04 07:40 UTC, jonpas requested changes
Background of UI preview image looks wrong.

`UI` should be lower-cased `ui`.

2020-11-04 07:40 UTC, jonpas commented on optionals/variants_cup/config.cpp
> +        authors[] = {"CUP Team", "GilleeDoo", "Tyrone"};
```suggestion
        authors[] = {"GilleeDoo", "Tyrone"};
```
We don't put it in Arcadian either. It is mentioned in the `README.md` - stick to "authors of what was added in this mod".

2020-11-04 07:40 UTC, jonpas commented on optionals/variants_cup/CfgVehicles.hpp
> +                factions[] = {};
Why empty?

2020-11-04 07:40 UTC, jonpas commented on optionals/variants_cup/CfgVehicles.hpp
> +        editorPreview = QPATHTOF(UI\C130J_B_Theseus.jpg);
```suggestion
        editorPreview = QPATHTOF(ui\C130J_B_Theseus.jpg);
```

2020-11-04 08:56 UTC, TyroneMF commented on optionals/variants_cup/CfgVehicles.hpp
> +                factions[] = {};
Fixed in next commit.

2020-11-06 07:23 UTC, jonpas reviewed
Need to take a look at preview image color grading.

2020-11-06 09:44 UTC, TyroneMF commented
Can't replicate the BI color grading, always comes out the same for me.

2020-11-06 11:07 UTC, jonpas commented on optionals/variants_cup/config.cpp
> +        units[] = {};
Shouldn't the vehicle be here for Zeus?

2020-11-06 12:54 UTC, jonpas approved these changes

2020-11-06 12:58 UTC, merged