Units - Additional Rvmat & SMDI for Atacs uniforms
Theseus-Aegis/TheseusServices pull request #152
Opened 2021-02-05 09:53 UTC by TyroneMF

- New base classes for Long/Rolled Atacs uniforms
- Changes how reflective parts of the uniform are.
![107410_20210205100919_1](https://user-images.githubusercontent.com/29175040/107018127-f1d62d00-6797-11eb-945b-3ee807ce8e15.png)

(Combat rvmat on the left, atacs on the right.)

2021-02-05 15:51 UTC, jonpas requested changes

2021-02-05 15:51 UTC, jonpas commented on addons/units/data/uniform_combat_atacs.rvmat
> +{
This file has to be cleaned up to standards.
- Indentation
- Braces position
- Spaces between numbers

2021-02-05 15:51 UTC, jonpas commented on addons/units/items/base_helpers.hpp
> +class CLASS(Unit_Combat_LS_Atacs_Base): CLASS(Unit_Combat_LS_Base) {
```suggestion
class CLASS(Unit_Combat_LS_ATACS_Base): CLASS(Unit_Combat_LS_Base) {
```
And everywhere else.

2021-02-06 02:21 UTC, jonpas approved these changes

2021-02-06 02:22 UTC, jonpas reviewed
I thought we are doing this for all uniforms?

2021-02-06 02:22 UTC, jonpas commented on addons/units/items/base_helpers.hpp
> +
```suggestion
```

2021-02-06 08:18 UTC, TyroneMF commented
> 
> 
> I thought we are doing this for all uniforms?

I have no idea tbh. Might be on a case by case basis but these are for the ATACS stuff specifically.

2021-02-06 10:10 UTC, jonpas approved these changes
Right, we fixed ambient and defuse in another PR, woops!

2021-02-06 11:11 UTC, merged