Add Insignia
Theseus-Aegis/TheseusServices pull request #155
Opened 2021-02-23 14:21 UTC by Lairdd1989

**When merged this pull request will:**
Adds following insignia

-Brand Of Sacrifice
-Bridge Four
-I Am Unstoppable
-Judge
-Natural Twenty
-Never Forget
-Raptor Squad

Thanks to Mick and Charley for pointers and tips

2021-02-23 15:48 UTC, TyroneMF requested changes

2021-02-23 15:48 UTC, TyroneMF commented on addons/insignias/CfgUnitInsignia.hpp
> +		class CLASS(Insignia_iamunstoppable) {
Indentation & Tabs.

2021-02-23 15:48 UTC, TyroneMF commented on addons/insignias/CfgUnitInsignia.hpp
> +		class CLASS(Insignia_judge) {
Again.

2021-02-23 15:48 UTC, TyroneMF commented on addons/insignias/CfgUnitInsignia.hpp
> +		class CLASS(Insignia_naturaltwenty) {
Again.

2021-02-23 15:48 UTC, TyroneMF commented on addons/insignias/CfgUnitInsignia.hpp
> +		class CLASS(Insignia_neverforget) {
And again.

2021-02-23 15:59 UTC, TyroneMF approved these changes
Looks fine to me.

2021-02-24 11:00 UTC, jonpas requested changes

2021-02-24 11:00 UTC, jonpas commented on addons/insignias/CfgUnitInsignia.hpp
> +    class CLASS(Insignia_raptorsquad) {
```suggestion
    class CLASS(Insignia_RaptorSquad) {
```

2021-02-24 11:01 UTC, jonpas requested changes

2021-02-24 11:01 UTC, jonpas commented on addons/insignias/CfgUnitInsignia.hpp
> +        displayName = "Brand of Sacrifice";
```suggestion
        displayName = "Brand Of Sacrifice";
```

2021-02-24 11:01 UTC, jonpas approved these changes

2021-02-24 11:04 UTC, merged