Add heli pilot coveralls
Theseus-Aegis/TheseusServices pull request #157
Opened 2021-04-04 22:18 UTC by JoramD0

**When merged this pull request will:**
- Title

2021-04-04 22:28 UTC, jonpas requested changes
4 unused files?
- `coveralls_Theseus_black_co.png`
- `coveralls_Theseus_green_co.png`
- `coveralls_Theseus_grey_co.png`
- `coveralls_Theseus_khaki_co.png`

2021-04-05 07:59 UTC, TyroneMF requested changes

2021-04-05 07:59 UTC, TyroneMF commented on addons/units/config.cpp
> +            QCLASS(Item_Uniform_HeliPilotCoveralls_Grey),
```suggestion
            QCLASS(Item_Uniform_HeliPilotCoveralls_Black),
```

2021-04-05 07:59 UTC, TyroneMF commented on addons/units/config.cpp
> +            QCLASS(Item_Uniform_HeliPilotCoveralls_Grey),
```suggestion
            QCLASS(Item_Uniform_HeliPilotCoveralls_Green),
```

2021-04-05 07:59 UTC, TyroneMF commented on addons/units/config.cpp
> +            QCLASS(Item_Uniform_HeliPilotCoveralls_Grey),
```suggestion
            QCLASS(Item_Uniform_HeliPilotCoveralls_Sand),
```

2021-04-05 08:41 UTC, TyroneMF approved these changes

2021-04-05 10:47 UTC, jonpas approved these changes

2021-04-05 10:47 UTC, merged